### ISSUE TITLE
Pipeline erstellen SP-13

### ISSUE THREAD

**Issue by Blend-Sal** [Narexos/Softwaretechnik-II#39]
AK01: Alle Tests im Repository müssen in der Pipeline mit angezeigt und getestet werden.

**Comment by IGreszta** [comment]
No Dockerfile, using GitHub actions and a DockerHub repository. For this we have made an "Asta - Shop" Account.
DockerHub Repository link: https://hub.docker.com/r/softwaretechnik2astashop/astah-shop
