### ISSUE TITLE
LF – 110 – Mitarbeiter ändert Produktinformationen SP-8

### ISSUE THREAD

**Issue by Blend-Sal** [Narexos/Softwaretechnik-II#6]
Als Mitarbeiter möchte ich die Möglichkeit haben, Produktinformationen ohne Probleme zu ändern, sodass das Sortiment flexibel sein kann.

**Comment by trom-peter** [comment]
Ursprüngliche AK01, AK02 nach Absprache mit dem Product Owner entfernt und verändert:

AK01: Das Speichern soll übernommen und korrekt angezeigt werden.
AK02: Änderungen können trotzdem nach Bedarf geändert werden und auch nur vom Mitarbeiter.
